// Public surface of the new core architecture
export { useAppStore } from './store/appStore';
export * from './store/types/events';
export * from './store/types/state';
export * from './store/selectors';
export { eventDispatcher } from './services/events/eventDispatcher';
export { generateRecommendations } from './domain/recommendations/generateRecommendations';
export { generateInsights } from './domain/insights/generateInsights';
export { buildAIContext } from './domain/ai/buildAIContext';
export { buildStateSnapshot } from './domain/state/buildStateSnapshot';
export { buildPredictions } from './domain/state/buildPredictions';
export { buildTrajectory } from './domain/state/buildTrajectory';
export { buildDailyTimeline } from './domain/state/buildDailyTimeline';
export { deriveLocalInsights } from './services/insights';
export { useUnifiedState } from './hooks/useUnifiedState';
export { useStateSnapshot } from './hooks/useStateSnapshot';
export { useRecommendations } from './hooks/useRecommendations';
export { useInterventionActions } from './hooks/useInterventionActions';
export { useScores } from './hooks/useScores';
export { usePredictions } from './hooks/usePredictions';
export { useTrajectory } from './hooks/useTrajectory';
export { useInsights } from './hooks/useInsights';
export { useEventLogger } from './hooks/useEventLogger';
export { useCoreSync } from './hooks/useCoreSync';
// Intervention system
export { scoreRecommendation } from './interventions/recommendations/scoreRecommendation';
export { rankRecommendations } from './interventions/recommendations/rankRecommendations';
export { evaluateOutcome } from './interventions/outcomes/evaluateOutcome';
export { recordInteraction, processPendingOutcomes } from './interventions/learning/updateInterventionLearning';
export { buildEffectTimeline } from './interventions/effects/interventionEffectTimeline';
export { buildResistanceProfile } from './interventions/adherence/behavioralResistanceModel';
export type { InterventionMemory, InterventionRecord } from './interventions/learning/interventionMemory';
export { EMPTY_INTERVENTION_MEMORY } from './interventions/learning/interventionMemory';
