// Public surface of the new core architecture
export { useAppStore } from './store/appStore';
export * from './store/types/events';
export * from './store/types/state';
export * from './store/selectors';
export { eventDispatcher } from './services/events/eventDispatcher';
export { generateRecommendations } from './domain/recommendations/generateRecommendations';
export { generateInsights } from './domain/insights/generateInsights';
export { buildAIContext } from './domain/ai/buildAIContext';
export { buildStateSnapshot } from './domain/state/buildStateSnapshot';
export { buildPredictions } from './domain/state/buildPredictions';
export { buildTrajectory } from './domain/state/buildTrajectory';
export { buildDailyTimeline } from './domain/state/buildDailyTimeline';
export { deriveLocalInsights } from './services/insights';
export { useUnifiedState } from './hooks/useUnifiedState';
export { useStateSnapshot } from './hooks/useStateSnapshot';
export { useRecommendations } from './hooks/useRecommendations';
export { useScores } from './hooks/useScores';
export { usePredictions } from './hooks/usePredictions';
export { useTrajectory } from './hooks/useTrajectory';
export { useInsights } from './hooks/useInsights';
export { useEventLogger } from './hooks/useEventLogger';
export { useCoreSync } from './hooks/useCoreSync';
